name: GiftBond
version: 1.1.0
main: com.fredygraces.giftbond.GiftBond
api-version: 1.21
author: Fredy_Graces
description: |
  Sistema avanzado de regalos y amistad con:
  • Puntos de amistad y ranking
  • Sistema de mailbox para regalos pendientes
  • Boosts permanentes y temporales
  • Economía integrada con SQLite
  • Regalos aleatorios inteligentes
  • Historial de regalos
website: https://github.com/fredygraces/GiftBond
# ™️ COPYRIGHT AND LICENSE INFORMATION
# This software is copyrighted © 2026 Fredy_Graces
# Unauthorized distribution, modification, or reverse engineering is prohibited
# See LICENSE file for full terms and conditions
depend: [PlaceholderAPI]
softdepend: [Vault, DiscordSRV]

commands:
  giftbond:
    description: Main GiftBond command with all subcommands
    usage: /giftbond <friends|top|send|redeem|reload|savedata|points|boost|debug>
    aliases: [gb]

permissions:
  giftbond.user:
    description: Permiso básico para usuarios normales
    default: true
    children:
      giftbond.friends: true
      giftbond.top: true
      giftbond.send: true
      giftbond.redeem: true
  
  giftbond.friends:
    description: Ver puntos de amistad
    default: false
    
  giftbond.top:
    description: Ver ranking de parejas
    default: false
    
  giftbond.send:
    description: Enviar regalos a otros jugadores
    default: false
    
  giftbond.redeem:
    description: Reclamar regalos pendientes
    default: false
  
  giftbond.use:
    description: Permiso general del plugin (deprecated)
    default: true
    children:
      giftbond.user: true
  
  giftbond.savedata:
    description: Permiso para crear backups manuales de la base de datos
    default: op
    
  giftbond.admin.points:
    description: Permiso para administrar puntos personales
    default: op
    
  giftbond.points.view:
    description: Permiso para ver puntos de otros jugadores
    default: true
    
  giftbond.admin.boost:
    description: Permiso para dar boosts temporales a jugadores
    default: op
    
  giftbond.admin.reload:
    description: Permiso para recargar el plugin
    default: op
    
  giftbond.admin.debug:
    description: Permiso para controlar el modo debug
    default: op
    
  giftbond.boost.vip:
    description: Boost permanente VIP (x1.5)
    default: false
    
  giftbond.boost.premium:
    description: Boost permanente Premium (x2.0)
    default: false
    
  giftbond.boost.ultra:
    description: Boost permanente Ultra (x3.0)
    default: false
    
  giftbond.admin:
    description: Permiso principal de administración
    default: op
    children:
      giftbond.admin.reload: true
      giftbond.savedata: true
      giftbond.admin.points: true
      giftbond.admin.boost: true
      giftbond.admin.debug: true