name: GiftBond
version: 1.1.0
main: com.fredygraces.giftbond.GiftBond
api-version: 1.21
author: Fredy_Graces
description: |
  Advanced gift and friendship system with:
  • Friendship points and ranking
  • Mailbox system for pending gifts
  • Permanent and temporary boosts
  • Integrated economy with SQLite
  • Smart random gifts
  • Gift history
website: https://github.com/fredygraces/GiftBond
# ™️ COPYRIGHT AND LICENSE INFORMATION
# This software is copyrighted © 2026 Fredy_Graces
# Unauthorized distribution, modification, or reverse engineering is prohibited
# See LICENSE file for full terms and conditions
depend: [PlaceholderAPI]
softdepend: [Vault, DiscordSRV]

commands:
  giftbond:
    description: Main GiftBond command with all subcommands
    usage: /giftbond <friends|top|send|redeem|reload|savedata|points|boost|debug>
    aliases: [gb]
  
  datasystem:
    description: Data system monitoring and testing commands
    usage: /datasystem <status|test|health>
    permission: giftbond.admin.datasystem

permissions:
  giftbond.user:
    description: Basic permission for regular users
    default: true
    children:
      giftbond.friends: true
      giftbond.top: true
      giftbond.send: true
      giftbond.redeem: true
  
  giftbond.friends:
    description: View friendship points
    default: false
    
  giftbond.top:
    description: View couples ranking
    default: false
    
  giftbond.send:
    description: Send gifts to other players
    default: false
    
  giftbond.redeem:
    description: Claim pending gifts
    default: false
  
  giftbond.use:
    description: General plugin permission (deprecated)
    default: true
    children:
      giftbond.user: true
  
  giftbond.savedata:
    description: Permission to create manual database backups
    default: op
    
  giftbond.admin.points:
    description: Permission to manage personal points
    default: op
    
  giftbond.points.view:
    description: Permission to view other players' points
    default: true
    
  giftbond.admin.boost:
    description: Permission to give temporary boosts to players
    default: op
    
  giftbond.admin.reload:
    description: Permission to reload the plugin
    default: op
    
  giftbond.admin.debug:
    description: Permission to control debug mode
    default: op
    
  giftbond.admin.datasystem:
    description: Permission to monitor and test data systems
    default: op
    
  giftbond.boost.vip:
    description: Permanent VIP boost (x1.5)
    default: false
    
  giftbond.boost.premium:
    description: Permanent Premium boost (x2.0)
    default: false
    
  giftbond.boost.ultra:
    description: Permanent Ultra boost (x3.0)
    default: false
    
  giftbond.admin:
    description: Main administration permission
    default: op
    children:
      giftbond.admin.reload: true
      giftbond.savedata: true
      giftbond.admin.points: true
      giftbond.admin.boost: true
      giftbond.admin.debug: true